apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laundry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Reynaldykalit/laundry_app
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: laundry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
