name: CI/CD Laundry App

on:
  push:
    branches:
      - main # Akan jalan otomatis saat Anda push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          # Ganti 'reynaldy' dengan username Docker Hub Anda
          docker build -t reynaldy/laundry-app:latest .
          docker push reynaldy/laundry-app:latest

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        # Bagian ini mensimulasikan koneksi ke cluster K8s
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to K8s
        run: |
          kubectl apply -f mysql-deploy.yaml
          kubectl apply -f laundry-deploy.yaml
          kubectl apply -f laundry-service.yaml
          # Memastikan Pod mengambil image terbaru yang baru dipush
          kubectl rollout restart deployment/laundry-deployment
